Feature: Feature file has a lot of commented lines
  In order to ignore lines
  As a commenter
  I want the scenarios to be ignore

#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
#  Ignored line
